name: Create liabilities

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Update package
        id: update_package
        run: |
          # Uninstall existing dependencies if any
          if npm ls --depth 0 --json | jq -e '.dependencies | length > 0' >/dev/null 2>&1; then
            npm ls --depth 0 --json | jq -r '.dependencies | keys[]' | xargs npm uninstall
          fi

          # Get the current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # Extract the numeric components of the version using regular expressions
          major=$(echo "$CURRENT_VERSION" | sed -E 's/^([0-9]+)\..*/\1/')
          minor=$(echo "$CURRENT_VERSION" | sed -E 's/^[0-9]+\.([0-9]+)\..*/\1/')
          patch=$(echo "$CURRENT_VERSION" | sed -E 's/^[0-9]+\.[0-9]+\.([0-9]+).*/\1/')

          # Increment the version components based on the rules
          if [ "$patch" -lt 9 ]; then
            # Increment the patch version
            NEW_VERSION="$major.$minor.$((patch + 1))"
          elif [ "$minor" -lt 9 ]; then
            # Increment the minor version and reset the patch version to 0
            NEW_VERSION="$major.$((minor + 1)).0"
          else
            # Increment the major version and reset the minor and patch versions to 0
            NEW_VERSION="$((major + 1)).0.0"
          fi

          # Determine the current vulnerability level
          VULNERABILITY_LEVEL=$(echo $CURRENT_VERSION | cut -d'-' -f2-)
          echo "Current vulnerability level: $VULNERABILITY_LEVEL"

          # Install the appropriate dependencies based on the vulnerability level
          if [[ $VULNERABILITY_LEVEL == "fixed" ]]; then
            npm install timespan@2.3.0 --save-exact
            NEW_VERSION="${NEW_VERSION}-low-vulnerability"
            VULNERABILITY_LEVEL="low-vulnerability"
            echo "vulnerability level was fixed, so we're going to low-vulnerability"

          elif [[ $VULNERABILITY_LEVEL == "low-vulnerability" ]]; then
            npm install swagger-ui-dist@4.1.2 --save-exact
            NEW_VERSION="${NEW_VERSION}-moderate-vulnerability"
            VULNERABILITY_LEVEL="moderate-vulnerability"
            echo "vulnerability level was low, so we're going to moderate-vulnerability"

          elif [[ $VULNERABILITY_LEVEL == "moderate-vulnerability" ]]; then
            npm install lodash@4.17.20 --save-exact
            NEW_VERSION="${NEW_VERSION}-high-vulnerability"
            VULNERABILITY_LEVEL="high-vulnerability"
            echo "vulnerability level was moderate, so we're going to high-vulnerability"

          elif [[ $VULNERABILITY_LEVEL == "high-vulnerability" ]]; then
            npm install lodash@4.17.4 --save-exact
            NEW_VERSION="${NEW_VERSION}-critical-vulnerability"
            VULNERABILITY_LEVEL="critical-vulnerability"
            echo "vulnerability level was high, so we're going to critical-vulnerability"

          elif [[ $VULNERABILITY_LEVEL == "critical-vulnerability" ]]; then
            NEW_VERSION="${NEW_VERSION}-deprecated"
            VULNERABILITY_LEVEL="deprecated"
            echo "vulnerability level was critical, so we're going to deprecated"

          else
            NEW_VERSION="${NEW_VERSION}-fixed"
            VULNERABILITY_LEVEL="fixed"
            echo "vulnerability level was deprecated, so we're going to fixed"
          fi

          echo "New version: $NEW_VERSION"
          echo "New vulnerability level: $VULNERABILITY_LEVEL"

          # Update the version in package.json
          npm version $NEW_VERSION --allow-same-version --no-git-tag-version

          # Authenticate with npm
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

          echo "vulnerability_level=$VULNERABILITY_LEVEL" >> "$GITHUB_OUTPUT"
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Push updated package.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Release ${{ steps.update_package.outputs.vulnerability_level }} version"
          git push

      - name: Publish the new version
        run: npm publish

      - name: Deprecate the version if necessary
        run: |
          if [[ ${{ steps.update_package.outputs.new_version }} == *"-deprecated" ]]; then
            npm deprecate liability@${{ steps.update_package.outputs.new_version }} "This version is deprecated"
          fi

        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
